package main

import (
	"fmt"
)

func genData() map[rune]uint64 {
	res := make(map[rune]uint64)
	for c := '!'; c <= '~'; c++ {
		v := uint64(0)
		for i := 0; i < 8; i++ {
			v = (v << 8) + uint64(Font8x8Basic[c][i])

		}

		res[c] = v
	}

	for c, arr := range Font8x8Block {
		v := uint64(0)

		for i := 0; i < 64; i++ {
			v = (v << 1) + uint64(arr[i])
		}

		res[c] = v
	}

	return res
}

func main() {
	fmt.Printf("// This file is automatically generated by github.com/rymis/ttyimg/genfont\n\n")
	fmt.Printf("package ttyimg\n\n")
	fmt.Printf("var drawFont = map[rune]uint64{\n")

	data := genData()

	for r, v := range data {
		if (r == '\'') {
			fmt.Print("\t'\\'': ")
		} else if (r == '\\') {
			fmt.Print("\t'\\\\': ")
		} else {
			fmt.Printf("\t'%c': ", r)
		}

		fmt.Printf("0x%016x,\n", v)
	}

	fmt.Printf("}\n")
}
